---
- name: "Manage NTP configuration"
  hosts: routers
  tasks:
    - name: "Apply NTP updates using jinja2 template"
      ios_config:
        src: "templates/ntp_config.j2"
      notify: "ntp_was_updated"
      register: "ntp_updates"

  handlers:
    - name: "Print changes since NTP was updated"
      listen: "ntp_was_updated"
      debug:
        var: ntp_updates.updates
