---
- name: "Collect information from router and print it"
  hosts: routers
  tasks:
    - name: "Run commands on router"
      ios_command:
        commands: "{{ commands }}"
      register: cli_output

    - name: "Print collected output"
      debug:
        var: cli_output.stdout_lines
